"""Generate docs/CATALOG.md — a human-readable snapshot of the harvested
repository: totals, breakdown by source / domain / format, and the full
City-of-Darwin Opendatasoft dataset list (the high-value real-time APIs).
"""
from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from .store import CatalogStore

REPORT_PATH = "docs/CATALOG.md"


def write_report(store: CatalogStore, path: str = REPORT_PATH) -> str:
    total = store.count()
    by_source = store.counts_by("source_system")
    by_domain = store.counts_by("domain")
    by_format = store.format_counts()
    spatial = store.conn.execute("SELECT COUNT(*) FROM datasets WHERE spatial = 1").fetchone()[0]
    generated = datetime.now(timezone.utc).isoformat(timespec="seconds")

    lines: list[str] = []
    a = lines.append
    a("# Public Data Repository — Catalog Snapshot")
    a("")
    a("> Auto-generated by `python -m ingestion.harvest --report`. Do not edit by hand.")
    a(f"> Generated: {generated}")
    a("")
    a(f"**Total datasets harvested: {total}**  ·  spatial datasets: {spatial}")
    a("")
    a("## By source")
    a("")
    a("| Source system | Datasets |")
    a("|---|---:|")
    for s, c in by_source:
        a(f"| `{s}` | {c} |")
    a("")
    a("## By operational domain")
    a("")
    a("| Domain | Datasets |")
    a("|---|---:|")
    for d, c in by_domain:
        a(f"| {d} | {c} |")
    a("")
    a("## By resource format")
    a("")
    a("| Format | Resources |")
    a("|---|---:|")
    for f, c in by_format:
        a(f"| {f or 'UNKNOWN'} | {c} |")
    a("")

    # Highlight the Opendatasoft crown jewels.
    ods = store.datasets_for_source("smart.darwin.nt.gov.au")
    if ods:
        a("## City of Darwin Smart Portal datasets (live queryable APIs)")
        a("")
        a("| Title | Domain | Records | Dataset id |")
        a("|---|---|---:|---|")
        for r in ods:
            rc = r["record_count"] if r["record_count"] is not None else ""
            a(f"| {r['title']} | {r['domain']} | {rc} | `{r['source_dataset_id']}` |")
        a("")

    out = Path(path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return str(out)
