-- 0007 seed: known-good NT government forms and how-to guides.
-- This gives the search a useful baseline from day one, before the scrapers run.
-- All URLs verified against nt.gov.au and darwin.nt.gov.au as of 2026.

INSERT OR IGNORE INTO forms (title, description, url, department, category, source_domain, keywords, last_scraped) VALUES
-- Driving & vehicles
('Driver Licence Application',          'Apply for an NT driver licence — new applicants and those converting from interstate.',           'https://nt.gov.au/driving/licences/get-an-nt-licence',                          'NT Transport',             'Driving Licences',       'nt.gov.au',         'driver licence apply new',       '2026-01-01'),
('Interstate Licence Conversion Form',  'Convert your interstate or overseas driving licence to an NT licence.',                          'https://nt.gov.au/driving/licences/converting-interstate-licence',              'NT Transport',             'Driving Licences',       'nt.gov.au',         'interstate convert transfer',    '2026-01-01'),
('Vehicle Registration Application',    'Register a new or transferred vehicle in the Northern Territory.',                               'https://nt.gov.au/driving/vehicle-registration/register-a-vehicle',             'NT Transport',             'Vehicle Registration',   'nt.gov.au',         'register vehicle car rego',      '2026-01-01'),
('Vehicle Transfer of Registration',    'Transfer vehicle registration when buying or selling a vehicle in the NT.',                      'https://nt.gov.au/driving/vehicle-registration/transfer-registration',          'NT Transport',             'Vehicle Registration',   'nt.gov.au',         'transfer rego sell buy vehicle', '2026-01-01'),
('Learner Licence Application',         'Apply for an NT learner driver licence (L plates).',                                            'https://nt.gov.au/driving/licences/learner-drivers',                            'NT Transport',             'Driving Licences',       'nt.gov.au',         'learner L plates young driver',  '2026-01-01'),
('Pay Traffic Fine',                    'Pay an NT traffic or parking infringement notice online.',                                       'https://nt.gov.au/driving/traffic-offences/pay-a-fine',                         'NT Transport',             'Traffic Offences',       'nt.gov.au',         'pay fine traffic parking',       '2026-01-01'),
-- Ochre Card / Working with Children
('Ochre Card Application',              'Apply for an NT Working with Children Clearance (Ochre Card). Required for most roles involving children in the NT.', 'https://nt.gov.au/law/child-protection/working-with-children-ochre-card/apply', 'Child Protection NT',  'Ochre Card',             'nt.gov.au',         'ochre card working children wwcc clearance', '2026-01-01'),
('Ochre Card Renewal',                  'Renew your NT Ochre Card before it expires.',                                                   'https://nt.gov.au/law/child-protection/working-with-children-ochre-card/renew', 'Child Protection NT',  'Ochre Card',             'nt.gov.au',         'ochre card renew expire',        '2026-01-01'),
-- Police checks
('NT Police Check Application',         'Apply for a National Police Certificate (police check) through NT Police.',                      'https://nt.gov.au/law/police/police-checks',                                    'NT Police',                'Police Checks',          'nt.gov.au',         'police check national certificate criminal history', '2026-01-01'),
-- Security licensing
('Security Industry Licence Application','Apply for a security industry licence in the Northern Territory — guard, crowd controller, etc.','https://nt.gov.au/law/security/apply-for-a-security-licence',                 'NT Police & Security',     'Security Licensing',     'nt.gov.au',         'security licence guard crowd controller apply', '2026-01-01'),
-- Births Deaths Marriages
('Register a Birth',                    'Register a new birth in the Northern Territory.',                                                'https://nt.gov.au/law/births-deaths-marriages/register-a-birth',                'Births Deaths Marriages',  'Births',                 'nt.gov.au',         'register birth baby newborn',    '2026-01-01'),
('Birth Certificate Application',       'Order a birth certificate for yourself or your child.',                                          'https://nt.gov.au/law/births-deaths-marriages/get-a-birth-certificate',         'Births Deaths Marriages',  'Births',                 'nt.gov.au',         'birth certificate order copy',   '2026-01-01'),
('Change of Name Application',          'Apply to change your name legally in the Northern Territory.',                                   'https://nt.gov.au/law/births-deaths-marriages/change-of-name',                  'Births Deaths Marriages',  'Name Change',            'nt.gov.au',         'change name legal deed poll',    '2026-01-01'),
('Marriage Certificate Application',    'Order a copy of a marriage certificate registered in the NT.',                                   'https://nt.gov.au/law/births-deaths-marriages/marriages',                       'Births Deaths Marriages',  'Marriages',              'nt.gov.au',         'marriage certificate copy order', '2026-01-01'),
-- Building & property
('Building Permit Application',         'Apply for a building permit for residential or commercial construction in the NT.',               'https://nt.gov.au/property/building-and-construction/building-permit',          'Department of Infrastructure','Building',             'nt.gov.au',         'building permit construct approve', '2026-01-01'),
('Owner-Builder Permit',                'Apply for an owner-builder permit to carry out your own building work.',                         'https://nt.gov.au/property/building-and-construction/owner-builder',            'Department of Infrastructure','Building',             'nt.gov.au',         'owner builder permit diy',       '2026-01-01'),
('Development Application',             'Lodge a development application for planning approval in the NT.',                               'https://nt.gov.au/property/planning/development-applications',                  'Department of Infrastructure','Planning',             'nt.gov.au',         'development application planning DA approval', '2026-01-01'),
('Land Title Transfer',                 'Transfer a land title when buying or selling property in the NT.',                               'https://nt.gov.au/property/land-titles/transfer-land',                          'Department of Infrastructure','Land Titles',          'nt.gov.au',         'land title transfer property buy sell', '2026-01-01'),
-- Business
('Start a Business — Licences',         'Find the licences and permits you need to start or operate a business in the NT.',               'https://nt.gov.au/industry/start-a-business/licences-and-permits',             'Business NT',              'Business',               'nt.gov.au',         'business licence permit start register', '2026-01-01'),
('Liquor Licence Application',          'Apply for a liquor licence to sell or supply alcohol in the NT.',                                'https://nt.gov.au/industry/liquor/apply-for-a-licence',                         'NT Liquor Commission',     'Liquor Licensing',       'nt.gov.au',         'liquor licence alcohol sell supply', '2026-01-01'),
-- Employment
('NT WorkSafe Licence Application',     'Apply for a high-risk work licence through NT WorkSafe.',                                        'https://worksafe.nt.gov.au/licences-and-registrations/apply',                   'NT WorkSafe',              'WHS Licensing',          'worksafe.nt.gov.au','worksafe licence high risk work', '2026-01-01'),
('Workers Compensation Claim',          'Lodge a workers compensation claim after a workplace injury in the NT.',                         'https://worksafe.nt.gov.au/compensation/claim',                                 'NT WorkSafe',              'Workers Compensation',   'worksafe.nt.gov.au','workers compensation claim injury workplace', '2026-01-01'),
-- Darwin City Council
('Dog Registration — Darwin',           'Register your dog with Darwin City Council (required annually).',                                'https://www.darwin.nt.gov.au/services/animals-and-wildlife',                    'Darwin City Council',      'Animals',                'darwin.nt.gov.au',  'dog registration pet council darwin', '2026-01-01'),
('Rates — Darwin City Council',         'Pay your council rates or apply for a rates rebate in Darwin.',                                  'https://www.darwin.nt.gov.au/services/rates',                                   'Darwin City Council',      'Rates',                  'darwin.nt.gov.au',  'rates council pay rebate darwin', '2026-01-01'),
('Development Application — Darwin',    'Lodge a development application with Darwin City Council.',                                      'https://www.darwin.nt.gov.au/services/building-and-planning',                   'Darwin City Council',      'Building',               'darwin.nt.gov.au',  'development application darwin building planning', '2026-01-01'),
-- Environment
('Firearms Licence Application',        'Apply for a firearms licence in the Northern Territory.',                                        'https://nt.gov.au/law/firearms/apply-for-licence',                              'NT Police',                'Firearms',               'nt.gov.au',         'firearms gun licence apply',     '2026-01-01'),
('Fishing Licence Application',         'Apply for a commercial or recreational fishing licence in the NT.',                              'https://nt.gov.au/industry/fishing/licences-and-permits',                       'Primary Industry NT',      'Fishing',                'nt.gov.au',         'fishing licence recreational commercial', '2026-01-01'),
-- Legal aid
('Legal Aid Application',               'Apply for legal aid assistance in the Northern Territory.',                                      'https://nt.gov.au/law/legal-aid/apply',                                         'NT Legal Aid',             'Legal Aid',              'nt.gov.au',         'legal aid apply assistance lawyer', '2026-01-01'),
-- Housing
('Apply for Public Housing',            'Apply for NT Government public housing.',                                                        'https://nt.gov.au/wellbeing/housing/apply-for-housing',                         'NT Housing',               'Housing',                'nt.gov.au',         'public housing apply rent government', '2026-01-01'),
-- Education
('Enrol in an NT School',               'Enrol your child in a Northern Territory government school.',                                    'https://nt.gov.au/education/schools/enrol-in-school',                           'Education NT',             'Education',              'nt.gov.au',         'school enrol enrolment child education', '2026-01-01');

-- Seed how-to guides
INSERT OR IGNORE INTO howto_guides (title, summary, steps_json, links_json, category, tags, updated_at) VALUES
('How to convert an interstate driving licence to an NT licence',
 'If you move to the NT with a valid Australian interstate licence, you must convert it to an NT licence within 3 months. The process is quick and done at a Motor Vehicle Registry (MVR).',
 '["Check you have a current, valid interstate licence — it must not be expired or suspended.",
   "Gather ID: you need proof of identity (birth certificate or passport) and proof of NT residency (utility bill, lease, or bank statement with your NT address).",
   "Visit any NT Motor Vehicle Registry (MVR) office in person — Darwin, Alice Springs, Katherine, or Tennant Creek.",
   "Surrender your interstate licence at the counter.",
   "Pay the licence fee (fees vary by licence class — check the MVR fee schedule).",
   "Your NT licence is issued on the spot or mailed within a few days."]',
 '[{"label": "NT Driving Licences — MVR", "url": "https://nt.gov.au/driving/licences/converting-interstate-licence"},
   {"label": "MVR office locations", "url": "https://nt.gov.au/driving/licences/motor-vehicle-registry-locations"}]',
 'Driving Licences', 'convert interstate driving licence mvr nt', '2026-01-01'),

('How to apply for an Ochre Card (Working with Children) in the NT',
 'An Ochre Card is mandatory for anyone working or volunteering in a paid or unpaid role with children in the Northern Territory. You must have one before starting work — you cannot work while your application is pending.',
 '["Check if you need a card: most roles working with or near children require one. Volunteers and paid workers both need it.",
   "Gather your documents: 100 points of ID including one primary document (passport or birth certificate) and supporting documents.",
   "Apply online through the NT Government website or in person at a Territory Families office.",
   "Pay the application fee (free for volunteers, fee applies for paid workers — check current fee schedule).",
   "A criminal history check is automatically run as part of the application.",
   "Wait for the outcome — standard processing takes 2–6 weeks. You cannot start regulated work until you receive your card.",
   "Your card is valid for 5 years. Set a reminder to renew before expiry."]',
 '[{"label": "Apply for an Ochre Card — NT Government", "url": "https://nt.gov.au/law/child-protection/working-with-children-ochre-card/apply"},
   {"label": "Check if you need a card", "url": "https://nt.gov.au/law/child-protection/working-with-children-ochre-card"}]',
 'Ochre Card', 'ochre card wwcc working children apply nt clearance', '2026-01-01'),

('How to get a police check (National Police Certificate) in the NT',
 'A National Police Certificate (police check) lists any disclosable court outcomes from your criminal history. It is commonly required for employment, volunteering, and licensing applications.',
 '["Decide which type you need: most employers want a standard National Police Certificate. Some roles require an AFP check — confirm with your employer.",
   "Apply online through the NT Police website or in person at Darwin Police Station or any NT Police station.",
   "Complete the application form with your full legal name, date of birth, and current address.",
   "Provide 100 points of certified ID (e.g. passport, driver licence, birth certificate).",
   "Pay the fee (fee varies — check current NT Police schedule).",
   "Receive your certificate by email or post — standard turnaround is 5–10 business days.",
   "Note: police checks are point-in-time documents. Many employers require them to be less than 3 months old."]',
 '[{"label": "NT Police Checks", "url": "https://nt.gov.au/law/police/police-checks"}]',
 'Police Checks', 'police check national certificate criminal history employment', '2026-01-01'),

('How to apply for a security industry licence in the NT',
 'Anyone working as a security guard, crowd controller, or in another security role in the NT must hold a valid NT Security Industry Licence. Applications are managed through NT Police.',
 '["Check the licence type you need: crowd controller, security officer, security firm operator, or others — each requires a separate licence.",
   "Complete mandatory training first: you must hold a Certificate II in Security Operations (or equivalent) from a registered training organisation before applying.",
   "Obtain a National Police Certificate less than 3 months old.",
   "Download and complete the licence application form from the NT Police website.",
   "Attach certified copies of your ID, training certificate, and police check.",
   "Submit the application in person at Darwin Police Station Licensing, or by post.",
   "Pay the application fee.",
   "Processing takes 4–6 weeks. Do not work in a security role until your licence is issued."]',
 '[{"label": "Security Industry Licences — NT Police", "url": "https://nt.gov.au/law/security/apply-for-a-security-licence"},
   {"label": "Security industry overview", "url": "https://nt.gov.au/law/security/security-industry-licences"}]',
 'Security Licensing', 'security licence guard crowd controller apply nt police', '2026-01-01'),

('How to register your dog in Darwin',
 'All dogs in Darwin must be registered with Darwin City Council. Registration is required within one month of a dog turning 3 months old, or within one month of moving to Darwin.',
 '["Desex your dog if possible — lower registration fees apply for desexed dogs.",
   "Ensure your dog is microchipped (compulsory in the NT).",
   "Complete the dog registration form on the Darwin City Council website or at a Council office.",
   "Provide your contact details, the dog''s details (breed, age, colour), and microchip number.",
   "Pay the annual registration fee — fee depends on whether the dog is desexed and whether owner has a pensioner concession.",
   "Renew registration every year before 31 May."]',
 '[{"label": "Dog Registration — Darwin City Council", "url": "https://www.darwin.nt.gov.au/services/animals-and-wildlife"}]',
 'Animals', 'dog registration darwin council pet microchip desex', '2026-01-01'),

('How to apply for a building permit in the NT',
 'Most building work in the NT requires a building permit before work starts. This includes new buildings, extensions, renovations, and some structural alterations.',
 '["Check if your project needs a permit: minor work (like painting) does not. Structural work, new rooms, decks, and garages usually do.",
   "Engage a licensed building certifier (private certifier) — they assess your plans and issue the permit. Find one on the NT Building Practitioners Register.",
   "Prepare architectural drawings and engineering plans if required.",
   "Submit your permit application to your certifier with the required documents and fee.",
   "The certifier assesses the application and may request changes.",
   "Once approved, work can commence. The certifier will carry out mandatory inspections during construction.",
   "After final inspection, a Certificate of Occupancy is issued."]',
 '[{"label": "Building Permits — NT Government", "url": "https://nt.gov.au/property/building-and-construction/building-permit"},
   {"label": "Find a licensed certifier", "url": "https://nt.gov.au/property/building-and-construction"}]',
 'Building', 'building permit construct approval certifier nt', '2026-01-01'),

('How to pay rates in Darwin',
 'Darwin City Council rates are levied annually and can be paid in full or by quarterly instalments. Pensioner rebates are available for eligible residents.',
 '["Receive your annual rates notice by post or email (register for eRates on the Darwin City Council website to go paperless).",
   "Check if you are eligible for a pensioner rates rebate — apply once and it renews automatically.",
   "Choose your payment method: online (credit/debit card), BPAY, in person at a Council office, or by mail.",
   "For quarterly instalments: payments are due in September, December, March, and June.",
   "If you cannot pay on time, contact Council before the due date to discuss a payment arrangement.",
   "Unpaid rates attract interest and may result in debt recovery action."]',
 '[{"label": "Rates — Darwin City Council", "url": "https://www.darwin.nt.gov.au/services/rates"}]',
 'Rates', 'rates council darwin pay rebate pensioner quarterly', '2026-01-01'),

('How to enrol your child in an NT government school',
 'NT government schools are free for all children aged 5–17. Enrolment can be done online or in person at the school. Children must be enrolled by the start of Term 1.',
 '["Check the enrolment zone for your address — children are usually enrolled at their local government school.",
   "Contact the school directly to arrange enrolment, or complete the enrolment form online through the NT Education portal.",
   "Provide proof of the child''s age (birth certificate or passport), immunisation history statement, and proof of your address.",
   "If your child has special needs, contact the school''s special education team early to arrange support.",
   "Enrolment can happen at any time of year, but enrol as early as possible before Term 1.",
   "You will receive a confirmation letter and the school will contact you about orientation."]',
 '[{"label": "Enrol in an NT School", "url": "https://nt.gov.au/education/schools/enrol-in-school"}]',
 'Education', 'school enrol child education NT primary secondary', '2026-01-01'),

('How to apply for legal aid in the NT',
 'NT Legal Aid Commission provides free legal services to people who cannot afford a lawyer. You must meet income and merit tests. Applications can be lodged in person or by phone.',
 '["Check if your matter is covered: Legal Aid assists with criminal law, family law, and some civil matters.",
   "Check the income and assets test — your income and assets must fall below the Legal Aid guidelines. These are available on their website.",
   "Contact NT Legal Aid by phone (1800 019 343) or visit any office in Darwin, Alice Springs, Katherine, Tennant Creek, or Nhulunbuy.",
   "Complete an application form — staff can assist you to fill this in.",
   "Legal Aid will assess your matter on its merit (whether it has reasonable prospects of success).",
   "If approved, a solicitor will be assigned or you will be referred to a duty lawyer."]',
 '[{"label": "Apply for Legal Aid", "url": "https://nt.gov.au/law/legal-aid/apply"},
   {"label": "NT Legal Aid Commission", "url": "https://www.ntlac.nt.gov.au"}]',
 'Legal Aid', 'legal aid apply lawyer free assistance NT', '2026-01-01'),

('How to apply for NT public housing',
 'NT Government public housing is available to eligible low-income households. There is high demand and waiting times can be long. Apply early.',
 '["Check eligibility: you must be an NT resident, meet income and asset limits, and not own or part-own property.",
   "Contact Housing NT by phone (1800 000 already built into the number on the NT Gov website) or visit a Housing NT office.",
   "Complete a Housing Application Form — bring ID for all household members and proof of income.",
   "Your application is assessed and placed on the waiting list based on need and priority.",
   "Update your application any time your circumstances change (household size, income, health needs).",
   "When a property becomes available that matches your needs, you will be contacted and offered a tenancy."]',
 '[{"label": "Apply for Public Housing — NT Government", "url": "https://nt.gov.au/wellbeing/housing/apply-for-housing"},
   {"label": "Housing NT", "url": "https://nt.gov.au/wellbeing/housing"}]',
 'Housing', 'public housing apply NT government rent social', '2026-01-01');
