-- Seed: ~70 Northern Territory destinations across all categories

INSERT OR IGNORE INTO destinations (name, category, summary, description, address, region, website, hours, price, lat, lng, tips, source_url) VALUES

-- ── BEACHES ──────────────────────────────────────────────────────────────────
('Mindil Beach','beaches',
 'Darwin''s most iconic beach, famous for its spectacular sunset markets and stunning views across the Timor Sea.',
 'Mindil Beach is arguably Darwin''s most beloved stretch of sand. Every Thursday and Sunday evening during the dry season, the world-famous Mindil Beach Sunset Market transforms the foreshore into a vibrant festival of food, arts, crafts and entertainment. The beach itself is ideal for watching sunsets but not for swimming due to marine stingers and saltwater crocodiles.',
 'Gilruth Avenue, The Gardens, Darwin NT 0820','Darwin',
 'https://www.mindil.com.au','Sunrise to sunset daily','Free',
 -12.4384, 130.8376,
 'Arrive 1–2 hours before sunset for the best spot. Stinger season (Oct–May) — no swimming. Bring cash for the markets.',
 'https://northernterritory.com/darwin-and-surrounds/do/mindil-beach-sunset-market'),

('Casuarina Beach','beaches',
 'Darwin''s longest beach stretching 6 km — popular for walks, fishing and watching seasonal marine wildlife.',
 'Casuarina Beach is Darwin''s longest beach, a sweeping 6 km strip of white sand backed by casuarina trees. It''s a favourite for beach walks, jogging and watching marine life including dolphins and sea turtles. The nudist section at the northern end is one of Australia''s few legal nude beaches. Swimming is generally not recommended due to stingers.',
 'Casuarina Coastal Reserve, Darwin NT 0810','Darwin',
 'https://parksandwildlife.nt.gov.au/parks/find/casuarina-coastal-reserve','Sunrise to sunset','Free',
 -12.3618, 130.8821,
 'Best at low tide. Bring insect repellent at dawn/dusk. The coastal reserve has excellent walking tracks.',
 'https://northernterritory.com/darwin-and-surrounds/do/casuarina-beach'),

('Nightcliff Beach','beaches',
 'A relaxed local beach and foreshore park with a popular weekend market, playground, and panoramic sea views.',
 'Nightcliff Beach and its foreshore reserve is a beloved Darwin local hangout. The Sunday Nightcliff Market draws crowds for fresh produce and artisan goods. The beach is great for sunset walks and fishing. The seawall walk from Nightcliff to Rapid Creek is one of Darwin''s most popular exercise routes.',
 'Pavonia Place, Nightcliff NT 0810','Darwin',
 'https://www.darwin.nt.gov.au','Open 24 hours','Free',
 -12.3815, 130.8644,
 'Sunday markets run 8am–2pm. Bring a fishing rod — great for whiting and queenfish. Stunning for sunsets.',
 'https://northernterritory.com/darwin-and-surrounds/do/nightcliff'),

('Lee Point Beach','beaches',
 'A remote-feeling beach north of Darwin with great fishing, birdwatching and nesting sea turtles in season.',
 'Lee Point Beach sits at the northern tip of Darwin''s peninsula and offers a secluded escape. The beach is a nesting ground for flatback sea turtles between November and February. The adjoining Lee Point Reserve has walking tracks through monsoon vine forest. Popular with anglers after barra and trevally.',
 'Lee Point Road, Lee Point NT 0810','Darwin',
 'https://parksandwildlife.nt.gov.au','Sunrise to sunset','Free',
 -12.3262, 130.9001,
 'Turtle nesting season Nov–Feb — stay off the beach after dark. Bring your own water. 4WD recommended for some access tracks.',
 'https://northernterritory.com/darwin-and-surrounds/do/lee-point-reserve'),

('Dundee Beach','beaches',
 'A wild, remote beach 110 km south-west of Darwin — legendary for barramundi fishing and dramatic tidal flats.',
 'Dundee Beach is a remote coastal community 110 km south-west of Darwin, famous among fisherpeople for exceptional barramundi, mud crab and reef fish catches. The vast tidal flats expose kilometres of sand at low tide. Very limited facilities — bring everything you need. Best accessed during the dry season.',
 'Dundee Beach Rd, Dundee Beach NT 0840','Darwin Region',
 'https://northernterritory.com/darwin-and-surrounds/do/dundee-beach','Accessible year-round','Free',
 -12.8347, 130.3721,
 'Only accessible in dry season (May–Oct). No fuel or shops — bring all supplies. 4WD essential on some tracks.',
 'https://northernterritory.com/darwin-and-surrounds/do/dundee-beach'),

('Nhulunbuy (Gove) Beach','beaches',
 'Pristine remote beaches near Nhulunbuy on the Gove Peninsula — gateway to Arnhem Land.',
 'The Gove Peninsula near Nhulunbuy offers some of Australia''s most pristine and least-visited beaches. White sand, clear azure water and a backdrop of red bauxite cliffs. Yirrkala Beach, Macassan Beach and Ski Beach are local favourites. Access to deeper Arnhem Land requires a permit.',
 'Nhulunbuy NT 0881','Arnhem Land',
 'https://northernterritory.com/arnhem-land','Open daily','Free (permit required for Arnhem Land)',
 -12.1844, 136.7722,
 'A permit is required to enter Arnhem Land beyond the Gove Peninsula. Contact Northern Land Council.',
 'https://northernterritory.com/arnhem-land/do/nhulunbuy'),

-- ── WATERFALLS ────────────────────────────────────────────────────────────────
('Wangi Falls','waterfalls',
 'Litchfield''s most visited waterfall — twin cascades plunge into a large, swimmable plunge pool.',
 'Wangi Falls is the most popular swimming spot in Litchfield National Park. Two cascades drop from the escarpment into a large, crystal-clear plunge pool fringed by monsoon forest. Facilities include change rooms, toilets, a kiosk and BBQ areas. A short walk leads through monsoon vine forest to viewing platforms. The pool is closed during the wet season when floods make it dangerous.',
 'Litchfield National Park, NT 0822','Litchfield',
 'https://parksandwildlife.nt.gov.au/parks/find/litchfield','7am–7pm daily (dry season); seasonal closure wet season','Free (park entry free)',
 -13.1496, 130.6887,
 'Closed Nov–Mar (wet season). Arrive early — very busy on weekends. No glass containers near the water.',
 'https://northernterritory.com/litchfield-national-park/do/wangi-falls'),

('Florence Falls','waterfalls',
 'Twin plunging falls with a beautiful, shaded swimming hole accessible by a short walk or 135-step descent.',
 'Florence Falls features twin cascades plunging 15 metres into a shaded billabong framed by rainforest. The lookout provides dramatic views, while 135 steps lead down to the swimming hole. A 1.6 km one-way walk through monsoon forest from the carpark is the alternative route. The rock ledge waterfall makes it one of the most photogenic in Litchfield.',
 'Litchfield National Park, NT 0822','Litchfield',
 'https://parksandwildlife.nt.gov.au/parks/find/litchfield','7am–7pm daily','Free',
 -13.0906, 130.6779,
 'Take the longer monsoon forest walk back for a different perspective. Closed in wet season.',
 'https://northernterritory.com/litchfield-national-park/do/florence-falls'),

('Tolmer Falls','waterfalls',
 'A dramatic 60-metre cascade in Litchfield — viewable from a lookout but not swimmable (ghost bat habitat).',
 'Tolmer Falls plunges over 60 metres from the escarpment in a series of dramatic cascades. Although you cannot swim here (the cave beneath houses a colony of rare ghost bats), the lookout views are breathtaking. A 1.6 km circuit walk passes through woodland and past a smaller swimming hole at Tjaetaba Falls.',
 'Litchfield National Park, NT 0822','Litchfield',
 'https://parksandwildlife.nt.gov.au/parks/find/litchfield','Open daily','Free',
 -13.0642, 130.6548,
 'No swimming — ghost bat habitat. The lookout alone is worth the visit. Best in early dry season when the falls are still flowing strongly.',
 'https://northernterritory.com/litchfield-national-park/do/tolmer-falls'),

('Jim Jim Falls','waterfalls',
 'One of Australia''s most spectacular waterfalls — a 200m drop into a remote plunge pool in Kakadu.',
 'Jim Jim Falls is one of Australia''s most dramatic waterfalls, plunging almost 200 metres over an escarpment into a stunning rock-lined plunge pool. After the wet season, the falls are a raging torrent; in late dry season they may reduce to a trickle or stop entirely. The journey itself is part of the adventure — 4WD track + 1 km boulder scramble. Worth every effort.',
 'Jim Jim Falls Road, Kakadu NP, NT 0886','Kakadu',
 'https://parksaustralia.gov.au/kakadu/do/swimming/jim-jim-falls/','May–Nov (dry season only)','Kakadu pass required (~$40/vehicle)',
 -13.2720, 132.4955,
 '4WD essential. Arrive early — very limited parking. Wet season road (Nov–Apr) is closed. Allow a full day.',
 'https://northernterritory.com/kakadu/do/jim-jim-falls'),

('Twin Falls','waterfalls',
 'A remote Kakadu gem — boat across a gorge, then hike to two cascades split by a rock island.',
 'Twin Falls in Kakadu requires a boat crossing (included with 4WD access) followed by a walk through a palm-lined gorge to reach two dramatic cascades that split around a central rock island. The journey through the gorge is arguably the highlight. Swimming is permitted in the plunge pools in dry season.',
 'Twin Falls Rd, Kakadu NP, NT 0886','Kakadu',
 'https://parksaustralia.gov.au/kakadu/do/swimming/twin-falls/','May–Nov','Kakadu pass + boat fee (~$15/person)',
 -13.3138, 132.5388,
 '4WD required. Book the boat pontoon in advance during peak season. Combine with Jim Jim Falls for a full day.',
 'https://northernterritory.com/kakadu/do/twin-falls'),

('Edith Falls (Leliyn)','waterfalls',
 'A stunning multi-tiered waterfall in Nitmiluk with swimmable pools at different elevations.',
 'Leliyn (Edith Falls) is a beautiful series of cascades in Nitmiluk National Park, 40 km north of Katherine. The lower pool is the main swimming area — wide, clear and fed by a tumbling waterfall. An upper pool reached by a short walk offers a more secluded swim. The 8.6 km Sweetwater Pool walk continues to a remote plunge pool through savanna and rainforest.',
 'Edith Falls Rd, Nitmiluk NP, NT 0852','Katherine',
 'https://parksandwildlife.nt.gov.au/parks/find/nitmiluk','7am–7pm daily (dry season)','Free (NT resident pass or small fee)',
 -14.1740, 132.1040,
 'Arrive early on weekends — a local favourite. The upper pool walk takes only 20 minutes and is much quieter.',
 'https://northernterritory.com/katherine-and-surrounds/do/edith-falls'),

('Gunlom Falls','waterfalls',
 'Kakadu''s most iconic infinity pool — a tiered waterfall with a natural infinity pool overlooking the escarpment.',
 'Gunlom (Waterfall Creek) offers one of Australia''s most spectacular natural swimming experiences. The lower gorge has a large swimming hole with a beautiful waterfall. A steep 1.2 km climb leads to the upper pools — natural infinity pools perched on the escarpment edge with jaw-dropping views across Kakadu. Absolutely unmissable.',
 'Gunlom Rd, Kakadu NP, NT 0886','Kakadu',
 'https://parksaustralia.gov.au/kakadu/do/swimming/gunlom/','May–Nov','Kakadu pass required (~$40/vehicle)',
 -13.8327, 132.3085,
 '4WD required for the road access. Start the climb early morning to beat the heat. Upper pools are not fenced — take care near edges.',
 'https://northernterritory.com/kakadu/do/gunlom-waterfall-creek'),

('Tjaynera (Sandy Creek) Falls','waterfalls',
 'A secluded Litchfield waterfall reachable only by 4WD and a creek walk — rewards with a stunning plunge pool.',
 'Tjaynera Falls (also known as Sandy Creek Falls) is Litchfield''s most secluded waterfall, requiring a 4WD track and a short creek-bed walk. The payoff is a beautiful, deep plunge pool with a wide curtain waterfall backed by towering sandstone walls. Because of the access requirements it is far less crowded than Wangi or Florence.',
 'Sandy Creek Rd, Litchfield NP, NT 0822','Litchfield',
 'https://parksandwildlife.nt.gov.au/parks/find/litchfield','Open daily (4WD access)','Free',
 -13.2220, 130.7166,
 '4WD essential — road impassable in wet season. Bring water shoes for the creek walk. No facilities on site.',
 'https://northernterritory.com/litchfield-national-park/do/tjaynera-sandy-creek-falls'),

-- ── NATIONAL PARKS ────────────────────────────────────────────────────────────
('Kakadu National Park','national_parks',
 'Australia''s largest national park — a UNESCO World Heritage site of ancient rock art, waterfalls and wetlands.',
 'Kakadu National Park is Australia''s largest national park (20,000 km²) and one of the world''s great wilderness areas. Listed as both a natural and cultural UNESCO World Heritage Site, it encompasses 65,000 years of Aboriginal culture, ancient rock art at Ubirr and Nourlangie, spectacular wetlands, waterfalls, and extraordinary wildlife. Best visited in the dry season (May–October).',
 'Kakadu Hwy, Kakadu NT 0886','Kakadu',
 'https://parksaustralia.gov.au/kakadu/','Year-round; best May–Oct','~$40/vehicle/week',
 -12.9144, 132.3706,
 'Buy the Kakadu pass online to save time at entry. Plan at least 3–4 days. Fuel up at Jabiru — limited options inside the park.',
 'https://northernterritory.com/kakadu'),

('Litchfield National Park','national_parks',
 'A stunning park 100 km from Darwin with swimming waterfalls, magnetic termite mounds and ancient sandstone formations.',
 'Litchfield National Park is one of the NT''s most accessible and popular parks, just 100 km south of Darwin. Famous for its crystal-clear swimming holes at Wangi, Florence and Buley Rockhole, its magnetic termite mounds, and the dramatic Lost City sandstone formation. A day trip from Darwin is possible, but camping allows you to enjoy the park at its best.',
 'Litchfield Park Rd, Batchelor NT 0845','Litchfield',
 'https://parksandwildlife.nt.gov.au/parks/find/litchfield','Open year-round; best May–Oct','Free entry',
 -13.1100, 130.6700,
 'Wangi Falls is closed Nov–Mar. Pack insect repellent. The Tabletop Track is a 39 km multi-day walk for serious hikers.',
 'https://northernterritory.com/litchfield-national-park'),

('Nitmiluk (Katherine Gorge) National Park','national_parks',
 'A stunning gorge carved over millions of years — explore by canoe, cruise, or helicopter and swim in deep pools.',
 'Nitmiluk National Park centres on Katherine Gorge, a series of 13 interconnected gorges carved by the Katherine River through ancient sandstone. Explore by guided cruise, self-hire canoe, or helicopter. Swimming is permitted in designated areas. The Jatbula Trail is a famous 58 km multi-day walk from Katherine Gorge to Edith Falls.',
 'Nitmiluk National Park, Katherine NT 0852','Katherine',
 'https://parksandwildlife.nt.gov.au/parks/find/nitmiluk','Park open year-round; cruises May–Oct','Park entry free; cruises from ~$50',
 -14.3044, 132.4225,
 'Book gorge cruises in advance. Canoe hire available. Wear sun protection — little shade on the water.',
 'https://northernterritory.com/katherine-and-surrounds/do/katherine-gorge-nitmiluk-national-park'),

('Keep River National Park','national_parks',
 'A remote, lesser-known park near the WA border with ancient Aboriginal rock art and unique sandstone formations.',
 'Keep River National Park is a hidden gem near the Western Australian border, 185 km west of Katherine. The park contains some of the NT''s best Aboriginal rock art sites and extraordinary eroded sandstone formations resembling those of Purnululu (Bungle Bungles). The walking tracks are excellent and relatively uncrowded.',
 'Victoria Hwy, Keep River NP, NT 0852','Katherine Region',
 'https://parksandwildlife.nt.gov.au/parks/find/keep-river','Open year-round','Free',
 -15.8000, 129.1000,
 'Limited facilities — self-sufficient camping only. Combine with a trip to Kununurra in WA (45 min drive).',
 'https://northernterritory.com/katherine-and-surrounds/do/keep-river-national-park'),

('Gregory National Park','national_parks',
 'The NT''s second largest national park — dramatic gorges, wildlife and pastoral history in remote Victoria River country.',
 'Gregory National Park is the NT''s second largest park, encompassing dramatic gorge country along the Victoria River. The park contains fossil sites, Aboriginal rock art, and excellent wildlife spotting. The Victoria River Gorge is accessible by 2WD; the Bullita and Limestone Gorge sections require 4WD. Rich in pastoral history.',
 'Victoria Hwy, Gregory NT 0852','Victoria River',
 'https://parksandwildlife.nt.gov.au/parks/find/gregory','Open year-round','Free',
 -15.6880, 130.6830,
 'Victoria River Roadhouse is the main access point. Fuel and basic supplies available. Allow multiple days.',
 'https://northernterritory.com/katherine-and-surrounds/do/gregory-national-park'),

-- ── GORGES ────────────────────────────────────────────────────────────────────
('Katherine Gorge','gorges',
 'Thirteen spectacular sandstone gorges carved by the Katherine River — canoe, cruise or hike through them.',
 'Katherine Gorge (Nitmiluk) is one of Australia''s most spectacular gorge systems. Thirteen interconnected gorges carved through ancient Arnhem Land sandstone by the Katherine River. During the dry season the gorge is tranquil; in the wet it transforms into a raging torrent. Explore by cruise, canoe, helicopter, or on foot along cliff-top walking tracks.',
 'Nitmiluk Visitor Centre, Katherine NT 0850','Katherine',
 'https://nitmiluktours.com.au','Cruises: 9am, 11am, 1pm daily (May–Oct)','Cruises from $50; canoe hire from $30/hr',
 -14.3044, 132.4225,
 'The 2-gorge cruise is the most popular. Canoe hire lets you explore at your own pace. Freshwater crocodiles present — harmless if not provoked.',
 'https://northernterritory.com/katherine-and-surrounds/do/katherine-gorge-nitmiluk-national-park'),

('Standley Chasm','gorges',
 'A dramatic narrow chasm near Alice Springs that glows vivid orange at midday when the sun hits the walls.',
 'Standley Chasm (Angkerle Atwatye) is a spectacular narrow gorge in the West MacDonnell Ranges, 45 km west of Alice Springs. The walls of quartzite are only 9 metres apart and 80 metres high. At midday, direct sunlight illuminates the red and orange walls creating an extraordinary light show. An easy 1.5 km walk from the carpark.',
 'Namatjira Drive, Standley Chasm, NT 0872','Alice Springs Region',
 'https://standleychasm.com.au','8am–5pm daily','Adult $12, Child $5',
 -23.7090, 132.8940,
 'Arrive at midday (11am–1pm) for the famous orange glow effect. Café and gift shop at the entrance.',
 'https://northernterritory.com/alice-springs-and-surrounds/do/standley-chasm-angkerle'),

('Simpsons Gap','gorges',
 'A serene water gap in the West MacDonnell Ranges — a cool haven for black-footed rock wallabies.',
 'Simpsons Gap (Rungutjirba) is an ancient water gap in the West MacDonnell Ranges, 18 km west of Alice Springs. The gap cuts through towering quartzite ridges to a cool, shaded waterhole. It is one of the best places in the region to see black-footed rock wallabies — look on the rocky slopes around dawn and dusk. An excellent cycling/walking destination.',
 'Larapinta Drive, Simpsons Gap NT 0872','Alice Springs Region',
 'https://parksaustralia.gov.au/uluru/','5am–8pm daily','Free',
 -23.6940, 133.7100,
 'Rock wallabies are most active at dawn and dusk. Bring a bike — the 17 km sealed track from Alice Springs is excellent.',
 'https://northernterritory.com/alice-springs-and-surrounds/do/simpsons-gap'),

('Trephina Gorge','gorges',
 'A classic East MacDonnell gorge with red quartzite walls, ghost gums and great walking tracks.',
 'Trephina Gorge is one of the most beautiful in the East MacDonnell Ranges, 85 km east of Alice Springs. The gorge features brilliant red quartzite walls, ghost gums rooted in white sand, and a permanent waterhole. The Trephina Rim Walk (8 km) and Panorama Walk provide excellent views. Much quieter than the more visited West MacDonnells.',
 'Ross Hwy, Trephina NT 0870','Alice Springs Region',
 'https://parksandwildlife.nt.gov.au/parks/find/trephina-gorge','Open daily','Free',
 -23.5369, 134.3847,
 'Combine with John Hayes Rockhole (10 km further east). 4WD required for some sections in the gorge.',
 'https://northernterritory.com/alice-springs-and-surrounds/do/trephina-gorge'),

('Ormiston Gorge','gorges',
 'The West MacDonnells'' most dramatic gorge — towering red walls, a permanent waterhole and the famous Pound Walk.',
 'Ormiston Gorge is widely considered the most spectacular gorge in the West MacDonnell Ranges, 135 km west of Alice Springs. The gorge opens into Ormiston Pound, a broad valley ringed by dramatic red cliffs. The 7.5 km Pound Walk is a classic NT walk passing through the gorge, across the pound and back via the rim. The permanent waterhole is superb for swimming.',
 'Namatjira Drive, Ormiston NT 0872','Alice Springs Region',
 'https://parksandwildlife.nt.gov.au/parks/find/ormiston-gorge','Open daily','Free',
 -23.6099, 132.7217,
 'The Pound Walk takes 3–4 hours. Start early to beat the heat. Camping available at the adjacent campground.',
 'https://northernterritory.com/alice-springs-and-surrounds/do/ormiston-gorge'),

-- ── HOT SPRINGS ───────────────────────────────────────────────────────────────
('Mataranka Thermal Pool','hot_springs',
 'Crystal-clear, 34°C spring-fed thermal pools set in a magical palm rainforest — the NT''s top hot spring.',
 'Mataranka Thermal Pool is the most visited thermal spring in the Northern Territory. The spring flows at a constant 34°C through a beautiful stand of Livistona palms, creating a magical swimming experience. The turquoise water is crystal clear and rich in minerals. Set within Elsey National Park, the pools are accessible year-round and are best visited in the early morning.',
 'Elsey National Park, Mataranka NT 0852','Katherine Region',
 'https://parksandwildlife.nt.gov.au/parks/find/elsey','6am–8pm daily','Free (NT parks pass or $4 per person)',
 -14.9346, 133.1009,
 'Best visited before 9am to avoid crowds. Wear reef shoes — the bottom is slippery. Bring drinking water.',
 'https://northernterritory.com/katherine-and-surrounds/do/mataranka-thermal-pool'),

('Bitter Springs','hot_springs',
 'A stunning thermal spring in Elsey National Park — float downstream through crystal-clear 34°C water.',
 'Bitter Springs, just 2 km from Mataranka, offers a unique experience: float or wade downstream through a 500-metre channel of 34°C mineral-rich water between shady paperbark trees. Unlike the main thermal pool it''s less visited and the floating experience is utterly unique. Return upstream on the bank. Crocodile-free — monitored daily.',
 'Martin Road, Mataranka NT 0852','Katherine Region',
 'https://parksandwildlife.nt.gov.au/parks/find/elsey','6am–8pm daily','Free',
 -14.9234, 133.1222,
 'Wear a shirt to protect your back from sunburn while floating. Life jacket available on site. Very popular on weekends.',
 'https://northernterritory.com/katherine-and-surrounds/do/bitter-springs'),

('Douglas Hot Springs','hot_springs',
 'Natural hot springs in a remote setting south of Darwin — multiple pools at different temperatures.',
 'Douglas Hot Springs is a natural thermal spring complex within Douglas Daly Conservation Area, 170 km south of Darwin. Multiple springs feed pools ranging from pleasantly warm to very hot (60°C+). The cooler mixing zones provide the best swimming. The area is rich in birdlife and has an excellent campground on the Daly River.',
 'Douglas Daly Conservation Area, NT 0822','Darwin Region',
 'https://parksandwildlife.nt.gov.au/parks/find/douglas-daly','Open daily','Free',
 -13.7833, 131.2833,
 'Test the water temperature before entering — some vents are scalding. Best combined with a Daly River barramundi fishing trip.',
 'https://northernterritory.com/darwin-and-surrounds/do/douglas-hot-springs'),

-- ── MARKETS ───────────────────────────────────────────────────────────────────
('Mindil Beach Sunset Market','markets',
 'Darwin''s most celebrated market — international food stalls, arts, crafts and entertainment at sunset on the beach.',
 'Mindil Beach Sunset Market is one of Australia''s greatest outdoor markets and Darwin''s most iconic attraction. Over 60 food stalls serve cuisine from Indonesia, Malaysia, Thailand, India, Greece and beyond. 200+ arts and crafts stalls, live music and entertainment. The backdrop — a blazing sunset over the Timor Sea — is unforgettable. Runs April to October.',
 'Mindil Beach, Gilruth Avenue, Darwin NT 0820','Darwin',
 'https://mindil.com.au','Thu 5–10pm, Sun 4–9pm (Apr–Oct)','Free entry',
 -12.4384, 130.8376,
 'Arrive hungry — try the satay from Charlie''s, laksa and Vietnamese rolls. BYO blanket to watch the sunset. Limited parking — walk or bus.',
 'https://northernterritory.com/darwin-and-surrounds/do/mindil-beach-sunset-market'),

('Parap Village Market','markets',
 'Darwin''s favourite Saturday morning food market — a multicultural feast of Asian food and fresh local produce.',
 'Parap Village Market is Darwin''s best Saturday morning outing, renowned for its extraordinary variety of Asian food. Satay, laksa, nasi goreng, samosas, fresh tropical fruit, mango ice cream and NT buffalo products are just some of the offerings. A community institution for over 30 years. Compact and walkable within the Parap shopping precinct.',
 'Parap Shopping Village, Parap NT 0820','Darwin',
 'https://www.darwin.nt.gov.au/living-in-darwin/arts-culture/markets','Saturday 8am–2pm (year-round)','Free entry',
 -12.4169, 130.8561,
 'Arrive before 9am for the best selection. Coconut laksa and mango ice cream are must-tries. Street parking fills quickly.',
 'https://northernterritory.com/darwin-and-surrounds/do/parap-village-market'),

('Nightcliff Market','markets',
 'A Sunday morning community market with fresh produce, crafts and a great beachside atmosphere.',
 'The Nightcliff Market is a popular Sunday morning market beside the beach in the suburb of Nightcliff. Fresh tropical produce, plants, local art, clothing and food stalls. The relaxed family atmosphere and sea breeze make it a Darwin institution. Walk along the seawall before or after for extra coastal charm.',
 'Pavonia Place, Nightcliff NT 0810','Darwin',
 'https://www.darwin.nt.gov.au','Sunday 8am–2pm (year-round)','Free',
 -12.3814, 130.8645,
 'Great for tropical fruits at low prices. Kids'' entertainment sometimes available. Combine with a beach walk.',
 'https://northernterritory.com/darwin-and-surrounds/do/nightcliff-market'),

('Rapid Creek Market','markets',
 'Darwin''s largest fresh produce market — famous for exotic tropical fruits, Asian vegetables and cheap eats.',
 'Rapid Creek Market is Darwin''s biggest and busiest fresh produce market. Vietnamese, Chinese and Southeast Asian vegetables, herbs and tropical fruits are the highlight. Excellent cheap cooked food including Vietnamese banh mi, Chinese dumplings and Indian roti. Also has arts, crafts and clothing stalls. Buzzes every weekend.',
 'Trower Road, Rapid Creek NT 0810','Darwin',
 'https://www.darwin.nt.gov.au','Sunday 8am–2pm; Saturday 8am–12pm (year-round)','Free',
 -12.3799, 130.8734,
 'Best for fruit and Asian produce in Darwin. Bring a cooler bag for your purchases. Cash preferred at most stalls.',
 'https://northernterritory.com/darwin-and-surrounds/do/rapid-creek-market'),

-- ── CAMPING ───────────────────────────────────────────────────────────────────
('Litchfield National Park Camping','camping',
 'Multiple campgrounds near swimming waterfalls — from powered sites to bush camping in a stunning park.',
 'Litchfield National Park has several excellent campgrounds including Wangi Falls, Florence Falls and Buley Rockhole. The Wangi Falls campground has powered and unpowered sites with toilets and hot showers, and you wake up steps from one of the NT''s finest swimming holes. Bush camping is also available throughout the park.',
 'Litchfield National Park, NT 0822','Litchfield',
 'https://nt.gov.au/leisure/parks-reserves/find-a-park-to-visit/litchfield-national-park','Year-round (facilities best May–Oct)','Unpowered $10/night; powered $35/night',
 -13.1100, 130.6700,
 'Book ahead in peak season (Jun–Aug). Bring insect repellent. Generators permitted at Wangi Falls campground only.',
 'https://northernterritory.com/litchfield-national-park/stay/camping'),

('Kakadu Camping — Cooinda','camping',
 'Camp at the heart of Kakadu near Yellow Water Billabong, one of Australia''s premier wildlife viewing spots.',
 'Cooinda is Kakadu''s most popular camping area, ideally situated for Yellow Water Billabong cruises, Jim Jim Falls day trips and the Warradjan Cultural Centre. The campground has powered and unpowered sites, a swimming pool, restaurant, bar, and general store. Wallabies and birds visit the campsite at dawn and dusk.',
 'Kakadu Hwy, Cooinda NT 0886','Kakadu',
 'https://parksaustralia.gov.au/kakadu/plan/camping/','May–Oct (best); accessible year-round','$35–50/night (powered)',
 -13.1706, 132.5263,
 'Book well ahead in school holidays. The 6:45am Yellow Water cruise is the best wildlife experience in Kakadu.',
 'https://northernterritory.com/kakadu/stay/camping'),

('Nitmiluk Gorge Campground','camping',
 'Camp right at the start of Katherine Gorge — paddle, hike or cruise from your doorstep.',
 'The Nitmiluk Gorge campground sits at the entrance to Katherine Gorge, giving campers immediate access to canoe hire, gorge cruises, and the start of the Jatbula and other hiking trails. Facilities include powered and unpowered sites, amenities block with hot showers, camp kitchen, and a kiosk. One of the NT''s best positioned campgrounds.',
 'Nitmiluk National Park, Katherine NT 0852','Katherine',
 'https://parksandwildlife.nt.gov.au/parks/find/nitmiluk','Year-round (best May–Oct)','Unpowered $12/person; powered $40/site',
 -14.3044, 132.4225,
 'Sites near the gorge fill fast — book early. The dawn mist over the gorge is magical. Kangaroos will raid unattended food.',
 'https://northernterritory.com/katherine-and-surrounds/stay/nitmiluk-camping'),

('Elsey National Park Camping','camping',
 'Camp beside the Roper River and walk to Mataranka thermal pools — excellent fishing and birdwatching.',
 'Elsey National Park campground sits beside the clear Roper River near Mataranka. The thermal pools are a short walk away. The park is excellent for barramundi fishing (permit required), birdwatching and swimming in the various thermal springs including Bitter Springs and the main thermal pool. The "We of the Never Never" heritage trail traces the famous novel''s setting.',
 'Elsey National Park, Mataranka NT 0852','Katherine Region',
 'https://parksandwildlife.nt.gov.au/parks/find/elsey','Year-round','Unpowered $10/person; powered $25/site',
 -14.9346, 133.1009,
 'Fishing licenses and permits required for barramundi. The Roper River is tidal and has crocodiles downstream — check signage.',
 'https://northernterritory.com/katherine-and-surrounds/stay/elsey-national-park'),

-- ── FISHING ───────────────────────────────────────────────────────────────────
('Darwin Harbour Fishing','fishing',
 'World-class barramundi, mangrove jack and trevally fishing from Darwin''s waterways and harbour.',
 'Darwin Harbour and surrounding waterways offer outstanding fishing year-round. Barramundi, mangrove jack, queenfish, Spanish mackerel, trevally and salmon are the most targeted species. Numerous charter operators run half and full-day trips from Cullen Bay Marina and Frances Bay. Shore fishing from wharves and beaches is also popular.',
 'Cullen Bay Marina, Darwin NT 0820','Darwin',
 'https://www.ntfishingcharters.com.au','Year-round; best Oct–Apr for barra','Charter from $150/half day',
 -12.4524, 130.8261,
 'Darwin is in a Declared Fish Management Area — check size and bag limits at nt.gov.au/fishing. A recreational fishing licence is required.',
 'https://northernterritory.com/darwin-and-surrounds/do/fishing'),

('Daly River Barramundi Fishing','fishing',
 'The Daly River is considered one of Australia''s best barramundi fisheries — a legendary angling destination.',
 'The Daly River, 220 km south-west of Darwin, is widely regarded as one of Australia''s premier barramundi fishing destinations. The river''s tannin-stained waters support huge populations of barra, as well as saratoga, sooty grunter and catfish. Several fishing lodges on the river offer guided trips, accommodation and boat hire.',
 'Daly River NT 0822','Darwin Region',
 'https://northernterritory.com/darwin-and-surrounds/do/daly-river-fishing','Best Oct–Apr (post wet season)','Lodge packages from $200/night; day trips from $250',
 -13.7575, 130.6903,
 'A fishing licence is required. Size limits apply — 55 cm minimum for barra. Always ask locals about croc activity before wading.',
 'https://northernterritory.com/darwin-and-surrounds/do/daly-river-fishing'),

('Mary River Barramundi & Wildlife','fishing',
 'Fish for barramundi and spot saltwater crocodiles, sea eagles and jabiru in the Mary River wetlands.',
 'The Mary River system, 100 km east of Darwin, combines world-class barramundi fishing with extraordinary wildlife watching. The river and surrounding wetlands support Australia''s highest density of saltwater crocodiles, massive flocks of magpie geese, and dozens of other species. Several houseboats and lodges operate on the river. Boat ramp access at Corroboree Park.',
 'Mary River Road, NT 0822','Darwin Region',
 'https://northernterritory.com/darwin-and-surrounds/do/mary-river','Year-round; best post-wet (Apr–Jun)','Houseboat from $400/night; guided tours from $120',
 -12.7833, 131.6167,
 'Crocodiles are very common — never swim. A freshwater crocodile permit area — extra care near the saltwater tidal reaches.',
 'https://northernterritory.com/darwin-and-surrounds/do/mary-river'),

('Cobourg Peninsula Fishing','fishing',
 'Remote, pristine fishing in Garig Gunak Barlu National Park — accessible only by 4WD or light aircraft.',
 'The Cobourg Peninsula in Garig Gunak Barlu National Park offers some of the NT''s most remote and spectacular fishing. Spanish mackerel, GT, coral trout, barramundi and mud crabs can all be caught here. The area is jointly managed with the Arnhem Land Aboriginal Land Trust — a permit is required to enter. Only accessible by 4WD (long unsealed track) or light aircraft. Very limited visitor numbers.',
 'Cobourg Peninsula NT 0822','Arnhem Land',
 'https://parksandwildlife.nt.gov.au/parks/find/garig-gunak-barlu','May–Oct (track opens dry season)','Permit required; camping $20/person/night',
 -11.3167, 132.2333,
 'Plan 6+ months ahead — permits are limited. The track from Darwin is 560 km of partly unsealed road. Self-sufficient camping only.',
 'https://northernterritory.com/arnhem-land/do/cobourg-peninsula'),

-- ── CRUISES ───────────────────────────────────────────────────────────────────
('Darwin Harbour Sunset Cruise','cruises',
 'Watch Darwin''s legendary sunset from the water on a relaxed harbour cruise with drinks and canapes.',
 'Darwin''s sunsets are world-famous, and viewing them from the harbour by boat is the definitive experience. Multiple operators run sunset cruises from Cullen Bay Marina and Stokes Hill Wharf, ranging from cocktail cruises to fishing and wildlife cruises. The colours as the sun sets behind the Timor Sea are extraordinary.',
 'Cullen Bay Marina, Darwin NT 0820','Darwin',
 'https://www.darwinharbourcruises.com.au','Daily departures (Apr–Oct, Fri–Sun year-round)','From $75/person',
 -12.4524, 130.8261,
 'Book at least a day ahead. Bring a light jacket — it can get breezy on the water. Best in the dry season for calm conditions.',
 'https://northernterritory.com/darwin-and-surrounds/do/darwin-harbour-cruises'),

('Adelaide River Jumping Crocodile Cruise','cruises',
 'Hand-feed massive saltwater crocodiles as they leap from the Adelaide River — a thrilling NT experience.',
 'The Adelaide River Jumping Crocodile Cruise is one of the NT''s most iconic tourist experiences. Crew dangle meat from poles to entice enormous saltwater crocodiles to leap from the water alongside the boat. Some of the crocs are over 5 metres long. Located 60 km south of Darwin on the Stuart Highway. Several operators run multiple departures daily.',
 'Stuart Highway, Adelaide River NT 0846','Darwin Region',
 'https://www.adelaiderivercruises.com.au','Multiple daily departures','Adult ~$45, Child ~$25',
 -12.6500, 131.2167,
 'Combine with a visit to the Australian War Memorial at Adelaide River township. Crocodiles are most active in the morning.',
 'https://northernterritory.com/darwin-and-surrounds/do/adelaide-river-jumping-crocodile'),

('Yellow Water Billabong Cruise (Kakadu)','cruises',
 'Australia''s finest wildlife cruise — glide through Kakadu''s billabong at dawn among crocodiles, birds and lilies.',
 'The Yellow Water (Ngurrungurrudjba) Billabong cruise in Kakadu is widely regarded as one of Australia''s best wildlife experiences. Dawn and early morning cruises reward passengers with extraordinary sightings: saltwater crocodiles, jabiru storks, sea eagles, jacanas, lotus birds, and hundreds of other species reflected in the mirror-still water. The landscape at sunrise is breathtaking.',
 'Cooinda, Kakadu NP, NT 0886','Kakadu',
 'https://kakadutourism.com/yellow-water-cruises','6:45am, 9am, 11:30am, 1pm, 3:30pm, 5:45pm daily','Adult $55, Child $30',
 -13.1706, 132.5186,
 'The 6:45am cruise has the best light and most wildlife activity. Book ahead — this is Kakadu''s most popular activity.',
 'https://northernterritory.com/kakadu/do/yellow-water-cruise'),

('Katherine Gorge Cruise','cruises',
 'Glide through ancient sandstone gorges with ancient rock art — a 2-gorge or full-day guided boat experience.',
 'Katherine Gorge cruises with Nitmiluk Tours take you deep into the UNESCO World Heritage listed gorge system. The 2-gorge cruise (2 hrs) is most popular, stopping at a freshwater crocodile viewing spot and ancient Aboriginal rock art. The full-day 4-gorge tour includes a swim in the gorge. Helicopter flights over the gorge are also offered.',
 'Nitmiluk Visitor Centre, Katherine NT 0850','Katherine',
 'https://nitmiluktours.com.au','Daily 9am, 11am, 1pm (May–Oct)','2-gorge from $55/adult; 4-gorge from $110/adult',
 -14.3044, 132.4225,
 'The early morning cruise has the best light for photography. Wear enclosed shoes for the portage between gorges.',
 'https://northernterritory.com/katherine-and-surrounds/do/katherine-gorge-cruise'),

-- ── WILDLIFE ──────────────────────────────────────────────────────────────────
('Territory Wildlife Park','wildlife',
 'Darwin''s premier wildlife park — see NT wildlife up close including crocs, quolls, bilbies and free-flying birds.',
 'Territory Wildlife Park at Berry Springs is one of the best wildlife parks in Australia, showcasing animals native to the Northern Territory. A 4 km walk (or tram ride) through naturalistic habitats gives close-up encounters with saltwater crocodiles, freshwater crocs, pythons, quolls, barramundi, and a spectacular free-flight bird show. The aquarium and nocturnal house are highlights.',
 'Cox Peninsula Road, Berry Springs NT 0838','Darwin Region',
 'https://territorywildlifepark.com.au','8:30am–4pm daily (last entry 3pm)','Adult $35, Child $18, Family $85',
 -12.6980, 130.9743,
 'Book the bird show (11am) and crocodile feed (2pm) into your schedule. The tram is worth taking — it covers more of the park.',
 'https://northernterritory.com/darwin-and-surrounds/do/territory-wildlife-park'),

('Crocosaurus Cove','wildlife',
 'Get in the Cage of Death with massive saltwater crocodiles in Darwin''s CBD — the ultimate croc experience.',
 'Crocosaurus Cove in Darwin''s city centre is home to some of Australia''s largest captive saltwater crocodiles. The star attraction is the Cage of Death — a perspex cylinder you descend into while a 5-metre croc swims around you. The facility also has snake encounters, a waterslide, and Australia''s largest reptile display. Safe for all ages — the cage is secure.',
 '58 Mitchell Street, Darwin NT 0800','Darwin',
 'https://www.crocosauruscove.com','9am–6pm daily (last entry 5pm)','Adult $38, Child $24; Cage of Death extra ($185/2 people)',
 -12.4638, 130.8424,
 'Book the Cage of Death well in advance — very popular. Feed sessions happen multiple times daily. Secure valuables in a locker.',
 'https://northernterritory.com/darwin-and-surrounds/do/crocosaurus-cove'),

('Fogg Dam Conservation Reserve','wildlife',
 'One of Australia''s best birdwatching sites — a dam teeming with magpie geese, herons and lotus lilies.',
 'Fogg Dam Conservation Reserve, 70 km east of Darwin, is one of Australia''s great birdwatching destinations. The dam wall walkway provides extraordinary views over a wetland teeming with magpie geese (100,000+ in peak season), jabiru, various herons, eagles, and spectacular lotus lily flowers. Dawn is the best time. Night tours are occasionally available for viewing cane toads and frogs.',
 'Arnhem Hwy, Fogg Dam NT 0822','Darwin Region',
 'https://parksandwildlife.nt.gov.au/parks/find/fogg-dam','Open daily (dawn–dusk)','Free',
 -12.5619, 131.3095,
 'Visit at dawn or dusk for the most spectacular bird concentrations. Bring binoculars and insect repellent. The wetlands are rich in crocodiles — stay on the wall.',
 'https://northernterritory.com/darwin-and-surrounds/do/fogg-dam'),

('Kakadu Wetlands & Wildlife','wildlife',
 'UNESCO-listed wetlands supporting 280 bird species, saltwater crocodiles and rare mammals in Kakadu.',
 'Kakadu''s floodplains and billabongs are among the most biologically rich wetlands on Earth, supporting one-third of Australia''s bird species, six species of sea turtles, over 60 mammal species and 117 species of reptiles. The Yellow Water Billabong, Mamukala Wetlands and Anbangbang Billabong are the main wildlife viewing areas. Peak season for birds is in the dry season.',
 'Kakadu National Park, NT 0886','Kakadu',
 'https://parksaustralia.gov.au/kakadu/do/wildlife/','Year-round; best May–Aug','Kakadu pass required (~$40/vehicle/week)',
 -12.9144, 132.3706,
 'Mamukala has an excellent bird hide. Evening drives on Kakadu Highway can yield wallabies, possums and owls.',
 'https://northernterritory.com/kakadu/do/wildlife'),

-- ── CULTURAL & ABORIGINAL ────────────────────────────────────────────────────
('Ubirr Rock Art (Kakadu)','cultural',
 'Ancient Aboriginal rock art spanning 20,000 years, with a spectacular escarpment sunset view over the floodplains.',
 'Ubirr contains some of the world''s finest and most accessible Aboriginal rock art, with paintings spanning over 20,000 years. The main galleries show X-ray style paintings of fish, kangaroos, thylacines and Mimi spirits. A short walk to the top of the escarpment provides a panoramic view over the floodplains — one of Australia''s most celebrated sunset vistas. Guided tours available.',
 'Kakadu National Park, NT 0886','Kakadu',
 'https://parksaustralia.gov.au/kakadu/do/culture/ubirr/','8:30am–sunset daily (Apr–Nov); reduced hours Dec–Mar','Kakadu pass required',
 -12.4083, 132.9917,
 'Arrive 90 minutes before sunset for the rock art and summit view. Ranger-guided walks depart daily — check the park visitor centre for times.',
 'https://northernterritory.com/kakadu/do/ubirr'),

('Nourlangie Rock Art (Kakadu)','cultural',
 'Kakadu''s most visited rock art site — dramatic paintings on an ancient sandstone overhang.',
 'Nourlangie (Burrunguy) is Kakadu''s most visited rock art site, featuring dramatic paintings on an ancient sandstone overhang including the famous Lightning Man (Namarrgon). The easy 1.5 km circuit walk passes multiple galleries of X-ray style paintings and the magnificent Anbangbang Billabong. Ranger-guided walks add context to the spiritual significance.',
 'Kakadu National Park, NT 0886','Kakadu',
 'https://parksaustralia.gov.au/kakadu/do/culture/nourlangie/','8am–sunset daily','Kakadu pass required',
 -12.8710, 132.8147,
 'Do this with the short Anbangbang Billabong walk for a perfect half-day. Early morning light is best for photography.',
 'https://northernterritory.com/kakadu/do/nourlangie'),

('Museum and Art Gallery of the NT','cultural',
 'Darwin''s premier cultural institution — showcasing NT art, natural history, Cyclone Tracy and maritime history.',
 'The Museum and Art Gallery of the Northern Territory (MAGNT) in Darwin is a must-visit cultural institution. Highlights include the Cyclone Tracy exhibition (the 1974 cyclone that destroyed Darwin), the Northern Territory collection of Aboriginal and Torres Strait Islander art, Pacific maritime culture, and natural history. Free entry to the permanent collection.',
 '19 Conacher Street, Fannie Bay NT 0820','Darwin',
 'https://www.magnt.net.au','Mon–Fri 9am–5pm; Sat–Sun 10am–5pm','Free (special exhibitions vary)',
 -12.4358, 130.8460,
 'Allow 2–3 hours for the main collection. The gift shop has excellent local art. Adjacent Fannie Bay Gaol museum is also worth a visit.',
 'https://northernterritory.com/darwin-and-surrounds/do/museum-and-art-gallery'),

('Tiwi Islands Cultural Tour','cultural',
 'Visit the Tiwi Islands — a unique Aboriginal culture with renowned art, sport and ceremonies.',
 'The Tiwi Islands (Bathurst and Melville Islands) are home to the Tiwi people, who have a distinct culture, language and art tradition unlike anywhere else in Australia. Cultural tours include visits to art centres where Tiwi pukumani poles, bark paintings and pottery are made, as well as cultural ceremonies and traditional land tours. Only accessible by flight or ferry from Darwin.',
 'Tiwi Islands NT 0822','Tiwi Islands',
 'https://tiwiislandstours.com.au','Tue, Thu, Sat (Apr–Oct; dry season only)','~$450–600/person including transfers',
 -11.4500, 130.7000,
 'Book through an authorised tour operator — self-guided access is restricted. The Grand Final of the Tiwi Islands Football League (Mar) is a unique cultural event.',
 'https://northernterritory.com/tiwi-islands/do/cultural-tours'),

('Uluru-Kata Tjuta National Park','cultural',
 'Australia''s most sacred and iconic landmark — two UNESCO-listed sacred Anangu sites in the Red Centre.',
 'Uluru (Ayers Rock) and Kata Tjuta (The Olgas) are Australia''s most recognisable natural icons and sacred sites of the Anangu traditional owners. Uluru is a 348-metre-high sandstone monolith that changes colour dramatically at sunrise and sunset. Kata Tjuta''s 36 domes span 21 km. Cultural walks, guided tours and the Mutitjulu waterhole offer deep cultural insights.',
 'Uluru-Kata Tjuta National Park, NT 0872','Alice Springs Region',
 'https://parksaustralia.gov.au/uluru/','Open daily (sunrise to sunset)','~$38/person for 3 days',
 -25.3444, 131.0369,
 'Climbing Uluru is permanently closed out of respect for the Anangu. Take the base walk (10.6 km) instead. Stay 2+ nights to see sunrise and sunset colours.',
 'https://northernterritory.com/red-centre/do/uluru-kata-tjuta'),

-- ── HIKING ────────────────────────────────────────────────────────────────────
('Larapinta Trail','hiking',
 'One of Australia''s greatest long-distance hikes — 223 km through the Red Centre''s ancient MacDonnell Ranges.',
 'The Larapinta Trail is a 223 km multi-day walking track through the West MacDonnell Ranges, one of Australia''s finest long-distance hikes. The trail passes through ancient gorges, along quartzite ridges and across open spinifex plains from Alice Springs Telegraph Station to Mt Sonder. It can be walked as day sections or as a full 12–16 day expedition.',
 'Alice Springs Telegraph Station, NT 0870','Alice Springs Region',
 'https://nt.gov.au/leisure/parks-reserves/find-a-park-to-visit/west-macdonnell-national-park','Apr–Sep (heat and water are serious issues other months)','Free; guided tours from $3,000',
 -23.6700, 133.8300,
 'Water caches along the trail may be unreliable — always carry 3L+ per person. Section 11 (Mt Sonder) is widely considered the most spectacular. Register your walk with the NT Police.',
 'https://northernterritory.com/alice-springs-and-surrounds/do/larapinta-trail'),

('Jatbula Trail','hiking',
 'A spectacular 58 km multi-day walk from Katherine Gorge to Edith Falls through monsoon rainforest and rock pools.',
 'The Jatbula Trail is one of Australia''s most beautiful multi-day walks, traversing 58 km from Nitmiluk (Katherine Gorge) to Leliyn (Edith Falls) through sandstone escarpment country, monsoon rainforest pockets, ancient rock art sites and crystal-clear natural pools. Takes 5–6 days. A total highlight of the NT.',
 'Nitmiluk Visitor Centre, Katherine NT 0850','Katherine',
 'https://nitmiluktours.com.au/walks/jatbula-trail','May–Oct only (track closes in wet season)','$25/person trail fee; camping $7/person/night',
 -14.3044, 132.4225,
 'One of Australia''s best walks — book months ahead as numbers are limited to 12 per day. Guided options available through Nitmiluk Tours.',
 'https://northernterritory.com/katherine-and-surrounds/do/jatbula-trail'),

('Litchfield Park Tabletop Track','hiking',
 'A 39 km multi-day walk over the Tabletop Range connecting Litchfield''s main attractions.',
 'The Tabletop Track is a 39 km loop walk over the Tabletop Range in Litchfield National Park, taking 2–3 days. The track connects Walker Creek, Reynolds River and the Greenant Creek campsites. Remote and lightly visited, it offers a wilderness experience close to Darwin. The track passes wildflower plains, escarpment views and several creek crossings.',
 'Litchfield National Park, NT 0822','Litchfield',
 'https://parksandwildlife.nt.gov.au/parks/find/litchfield','May–Sep only (track very muddy in wet)','Free (camping $10/person/night)',
 -13.1500, 130.6900,
 'Self-registration at the Litchfield Visitor Centre is required. Carry all water between water points. Limited shade on the plateau sections.',
 'https://northernterritory.com/litchfield-national-park/do/tabletop-track'),

-- ── ISLANDS ───────────────────────────────────────────────────────────────────
('Tiwi Islands','islands',
 'Two tropical islands north of Darwin — remote, culturally rich, with stunning beaches and unique Aboriginal art.',
 'Bathurst and Melville Islands make up the Tiwi Islands, just 80 km north of Darwin. The Tiwi people have one of Australia''s most distinctive cultures and artistic traditions, famous for carved pukumani poles, silk-screen fabrics and football. The islands have pristine tropical beaches, excellent fishing and unique wildlife. Access is by commercial flight from Darwin or the seasonal ferry.',
 'Tiwi Islands NT 0822','Tiwi Islands',
 'https://tiwiislandstours.com.au','Year-round; cultural tours Apr–Oct','Ferry ~$250 return; flights ~$350 return',
 -11.5000, 130.7500,
 'A permit is required for most of the islands. Organised tours handle the permits. The Nguiu art centre sells authentic Tiwi art.',
 'https://northernterritory.com/tiwi-islands'),

('Gove Peninsula & Nhulunbuy','islands',
 'A remote peninsula in northeast Arnhem Land — bauxite mining town surrounded by wild beaches and coral reefs.',
 'The Gove Peninsula and Nhulunbuy township in northeast Arnhem Land offer extraordinary natural beauty. Pristine beaches, coral reefs, excellent fishing and Yolngu cultural experiences are all available. The nearby Yirrkala community has one of Australia''s most important Aboriginal art centres. Access is by flight from Darwin or Cairns. Permits required for most of Arnhem Land.',
 'Nhulunbuy NT 0881','Arnhem Land',
 'https://northernterritory.com/arnhem-land/do/nhulunbuy','Year-round','Flights from Darwin ~$400 return',
 -12.1845, 136.7722,
 'Permits required for Arnhem Land beyond the Gove Peninsula — contact Northern Land Council at least 10 working days in advance.',
 'https://northernterritory.com/arnhem-land/do/nhulunbuy'),

-- ── FOOD & DINING ────────────────────────────────────────────────────────────
('Stokes Hill Wharf Precinct','food',
 'Darwin''s iconic waterfront dining precinct — fresh seafood, cold beers and harbour views on the historic wharf.',
 'Stokes Hill Wharf is Darwin''s most atmospheric dining and entertainment precinct, built over the waters of the inner harbour. Fresh barramundi, mud crab, oysters and tropical seafood are the specialties. The Friday night Fish Frenzy is a Darwin institution. The wharf is the departure point for many harbour cruises and has excellent Darwin Harbour views.',
 'Stokes Hill Wharf, Darwin NT 0800','Darwin',
 'https://www.stokeshillwharf.com.au','Daily 11am–10pm; Fish Frenzy Fri 5pm–9pm','Mains $25–55',
 -12.4706, 130.8452,
 'Friday night Fish Frenzy is very popular — arrive before 6pm for the best selection. Order the mud crab when in season (Jun–Nov).',
 'https://northernterritory.com/darwin-and-surrounds/eat/stokes-hill-wharf'),

('Hanuman Restaurant Darwin','food',
 'Darwin''s most celebrated restaurant — exquisite Thai and Indian Nonya cuisine in an elegant setting.',
 'Hanuman is widely regarded as Darwin''s finest restaurant, serving contemporary Thai and Indian Nonya cuisine since 1992. The menu features fresh local ingredients — local barramundi, NT buffalo, seasonal tropical produce — in complex, aromatic dishes. The restaurant has hosted international dignitaries and was named in Australia''s top restaurants. Reservations essential.',
 '28 Mitchell Street, Darwin NT 0800','Darwin',
 'https://www.hanuman.com.au','Mon–Fri 12pm–2:30pm; daily 6pm–10pm','Mains $35–55; degustation from $110',
 -12.4627, 130.8418,
 'Reserve at least a week ahead for weekend dinners. The Hanuman king prawn curry and coconut barramundi are signature dishes. Smart casual dress preferred.',
 'https://northernterritory.com/darwin-and-surrounds/eat/hanuman'),

('Cullen Bay Marina Dining','food',
 'Darwin''s sophisticated marina precinct — waterfront restaurants, wine bars and the best happy-hour sunset views.',
 'Cullen Bay Marina is Darwin''s most picturesque dining precinct, with restaurants, cafes and bars lining a marina filled with yachts and cruisers. Excellent seafood, international cuisine and cold tropical cocktails with harbour views. The precinct buzzes from late afternoon as the sunset crowd arrives. Many restaurants offer happy hour deals.',
 'Cullen Bay Marina, Darwin NT 0820','Darwin',
 'https://www.cullenbaymarina.com.au','Daily from 11am; best from 4pm','Varied; mains $25–50',
 -12.4524, 130.8261,
 'Table One, Pee Wee''s at the Point and Sails are consistently popular. Arrive before 5pm on weekends to get a waterfront table.',
 'https://northernterritory.com/darwin-and-surrounds/eat/cullen-bay-marina'),

('Alice Springs Night Markets','food',
 'Desert dining under the stars — seasonal Alice Springs night markets with NT bush tucker and local food.',
 'Alice Springs hosts seasonal night markets in its Todd Mall precinct, combining food stalls, local entertainment and the extraordinary Red Centre night sky. Bush tucker inspired dishes — including kangaroo, witchetty grubs, bush tomato and quandong — alongside multicultural food stalls create a unique outback dining experience. The Todd Mall Merchants also run year-round cafés and restaurants.',
 'Todd Mall, Alice Springs NT 0870','Alice Springs Region',
 'https://www.alicesprings.nt.gov.au','Seasonal (Jun–Aug); markets Fri evenings','Free entry',
 -23.6980, 133.8807,
 'Try bush tucker experiences at the Red Ochre Grill year-round. The Overlanders Steakhouse is famous for its Drover''s Blowout bush tucker feast.',
 'https://northernterritory.com/red-centre/eat/alice-springs');
